name: Boop

on:
  push:
    branches: [ "main", "github-actions" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-aarch64
            name: boop-Linux-aarch64
            os: ubuntu-22.04
            target: aarch64-unknown-linux-gnu
            bin: boop
            bin-rename: boop-Linux-aarch64
            command: build

          - release_for: Linux-x86_64
            name: boop-Linux-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            bin: boop
            bin-rename: boop-Linux-x86_64
            command: build

            #- release_for: macOS-aarch64
            #  name: boop-macOS-aarch64
            #  os: macOS-latest
            #  target: aarch64-apple-darwin
            #  bin: boop
            #  bin-rename: boop-macOS-aarch64
            #  command: both

          - release_for: macOS-x86_64
            name: boop-macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: boop
            bin-rename: boop-macOS-x86_64
            command: both

          - release_for: Windows-x86_64
            name: boop-Win64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: boop.exe
            bin-rename: boop-Win64.exe
            command: both

            # more release targets here ...
    runs-on: ${{ matrix.platform.os }}
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release --locked"
          strip: true

      - name: Rename Binary
        shell: bash
        run: |
          target=${{ matrix.platform.target }}
          bin_src=${{ matrix.platform.bin }}
          bin_dst=${{ matrix.platform.bin_rename }}
          mv target/$target/release/$bin_src bin/$bin_dst

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: bin/${{ matrix.platform.bin_rename }}
